services:
  backend:
    build:
      context: ./app-fast-api-ood
    ports:
      - "8000:8000"
    volumes:
      - ./app-fast-api-ood:/app
    environment:
      - DETECTOR_URL=http://detector:8500  # URL сервиса модели
    networks:
      - app_network

  frontend:
    build:
      context: ./front
    ports:
      - "4200:4200"  # Прокси на порт 4200 для фронтенда
    volumes:
      - ./front:/app
    environment:
      - API_URL=http://backend:8000  # URL API для бэкенда
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Прокси-сервер будет доступен на 80 порту
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Конфигурация для Nginx
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
